require "digest/md5"

require_relative "features/support/libs/mongo"

def to_md5(password)
  return Digest::MD5.hexdigest(password)
end

task :test do
  puts "Executando uma tarefa de teste"
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))
  users = [

    { name: "Max", email: "max@gmail.com", password: to_md5("mudar123") },
    { name: "Max", email: "max@hotmail.com", password: to_md5("mudar123") },
    { name: "Max", email: "max@ig.com", password: to_md5("mudar123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber -p jenkins"
end

task :hmg_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))
  users = [

    { name: "Max", email: "max@gmail.com", password: to_md5("mudar123") },
    { name: "Max", email: "max@hotmail.com", password: to_md5("mudar123") },
    { name: "Max", email: "max@ig.com", password: to_md5("mudar123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)
end
